version: "3.8"

services:
  db:
    image: postgres:15.3-alpine
    container_name: tech-trivia-database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - trivia
    volumes:
      - postgres_database:/var/lib/postgressql/data

  api:
    build: .
    container_name: tech-trivia-api
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_TIME_ZONE=${DB_TIME_ZONE}
      - DB_SSL_MODE=${DB_SSL_MODE}
      - APP_PORT=${APP_PORT}
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - db
    networks:
      - trivia

volumes:
  postgres_database:

networks:
  trivia:
    driver: bridge